chore: actions.yml 원래대로 수정

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -6,8 +6,8 @@ on:
   push:
     branches: [ "develop" ]
 
+# 테스트 결과 작성을 위해 쓰기권한 추가
 permissions: write-all
-
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -19,9 +19,6 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
-
-      - name: Clear Gradle Test Cache Only  # ✅ 특정 캐시만 삭제
-        run: rm -rf ~/.gradle/caches/modules-2/files-2.1
 
       - name: Set application.yml
         uses: microsoft/variable-substitution@v1
@@ -40,13 +37,14 @@ jobs:
           s3.secret-key: ${{ secrets.S3_SECRET_KEY }}
           s3.region: ${{ secrets.S3_REGION }}
 
+      # gradle을 캐싱 - 시간 단축
       - name: Gradle Caching
         uses: actions/cache@v3
         with:
           path: |
             ~/.gradle/caches
             ~/.gradle/wrapper
-          key: ${{ runner.os }}-gradle-${{ github.run_id }}
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
           restore-keys: |
             ${{ runner.os }}-gradle-
 
@@ -54,10 +52,11 @@ jobs:
         run: chmod +x gradlew
 
       - name: Build With Gradle
-        run: ./gradlew build -x test --no-daemon
+        run: ./gradlew build -x test
 
-      - name: Run Tests
-        run: ./gradlew --info test --no-daemon
+      # build Test
+      - name: 테스트 코드 실행
+        run: ./gradlew --info test
 
       - name: Publish Unit Test Results
         uses: EnricoMi/publish-unit-test-result-action@v1
@@ -67,7 +66,7 @@ jobs:
 
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v3
-        if: success() || failure()
+        if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: '**/build/test-results/test/TEST-*.xml'
 
